#pragma checksum "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4590807f1c619503d328bf35b1398a874ed90ab4"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Post), @"mvc.1.0.view", @"/Views/Home/Post.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/Post.cshtml", typeof(AspNetCore.Views_Home_Post))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\_ViewImports.cshtml"
using Neupusti.Models;

#line default
#line hidden
#line 2 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\_ViewImports.cshtml"
using Neupusti.Models.Comments;

#line default
#line hidden
#line 3 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\_ViewImports.cshtml"
using Neupusti.ViewModels;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"4590807f1c619503d328bf35b1398a874ed90ab4", @"/Views/Home/Post.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"90671c19739ae56edb6f25b842d68bb22b490878", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Post : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<Post>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 2 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml"
   
    ViewBag.Title = Model.Title;
    ViewBag.Description = Model.Description;
    ViewBag.Keywords = $"{Model.Tags?.Replace(",", " ")} {Model.Category}";

#line default
#line hidden
            BeginContext(178, 253, true);
            WriteLiteral("\r\n<section id=\"cover\">\r\n    <div id=\"cover-caption\">\r\n        <div id=\"container\" class=\"container\">\r\n            <div class=\"row text-black\">\r\n                <div class=\"col-sm-10 offset-sm-1 text-center\">\r\n\r\n                    <h1 class=\"display-4\">");
            EndContext();
            BeginContext(432, 11, false);
#line 14 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml"
                                     Write(Model.Title);

#line default
#line hidden
            EndContext();
            BeginContext(443, 113, true);
            WriteLiteral("</h1>\r\n                    <span class=\"fa fa-calendar\" aria-hidden=\"true\"> Posted: </span>\r\n                    ");
            EndContext();
            BeginContext(557, 33, false);
#line 16 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml"
               Write(Model.Created.ToShortDateString());

#line default
#line hidden
            EndContext();
            BeginContext(590, 92, true);
            WriteLiteral("\r\n                </div>\r\n\r\n                    <div class=\"post offset-sm-1 text-center\">\r\n");
            EndContext();
#line 20 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml"
                         if (!String.IsNullOrEmpty(Model.Image))
                        {
                            var image_path = $"/Image/{Model.Image}";

#line default
#line hidden
            BeginContext(846, 32, true);
            WriteLiteral("                            <img");
            EndContext();
            BeginWriteAttribute("src", " src=\"", 878, "\"", 895, 1);
#line 23 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml"
WriteAttributeValue("", 884, image_path, 884, 11, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(896, 17, true);
            WriteLiteral(" width=\"500\" />\r\n");
            EndContext();
#line 24 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml"
                        }

#line default
#line hidden
            BeginContext(940, 131, true);
            WriteLiteral("                    </div>\r\n                    <div class=\"post-body col-sm-10 offset-sm-1 text-center\">\r\n                        ");
            EndContext();
            BeginContext(1072, 20, false);
#line 27 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml"
                   Write(Html.Raw(Model.Body));

#line default
#line hidden
            EndContext();
            BeginContext(1092, 83, true);
            WriteLiteral("\r\n\r\n                    </div>\r\n                    <div class=\"comment section\">\r\n");
            EndContext();
#line 31 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml"
                          
                            await Html.RenderPartialAsync("_Comment", new CommentViewModel { PostId = Model.Id, Id = 0 });
                        

#line default
#line hidden
            BeginContext(1354, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 35 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml"
                         foreach (var c in Model.Comments)
                        {

#line default
#line hidden
            BeginContext(1443, 65, true);
            WriteLiteral("                            <p>\r\n                                ");
            EndContext();
            BeginContext(1509, 9, false);
#line 38 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml"
                           Write(c.Message);

#line default
#line hidden
            EndContext();
            BeginContext(1518, 5, true);
            WriteLiteral(" --- ");
            EndContext();
            BeginContext(1524, 9, false);
#line 38 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml"
                                          Write(c.Created);

#line default
#line hidden
            EndContext();
            BeginContext(1533, 36, true);
            WriteLiteral("\r\n                            </p>\r\n");
            EndContext();
#line 52 "C:\Users\Zhannel\source\repos\Neupusti\Neupusti\Views\Home\Post.cshtml"
                                    
                        }

#line default
#line hidden
            BeginContext(2249, 90, true);
            WriteLiteral("                    </div>\r\n                </div>\r\n        </div>\r\n    </div>\r\n</section>");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<Post> Html { get; private set; }
    }
}
#pragma warning restore 1591
